/* Insert statements for tables that should be populated during app startup */

/* How the coverage of a testing task will determine the status of the task */
INSERT INTO TestingCoverageStatusMap(Coverage, Status)
    VALUES
    (0, "open"),
    (1, "in progress"),
    (2, "in progress"),
    (3, "in progress"),
    (4, "in progress"),
    (5, "in progress"),
    (6, "in progress"),
    (7, "in progress"),
    (8, "in progress"),
    (9, "in progress"),
    (10, "in progress"),
    (11, "in progress"),
    (12, "in progress"),
    (13, "in progress"),
    (14, "in progress"),
    (15, "in progress"),
    (16, "in progress"),
    (17, "in progress"),
    (18, "in progress"),
    (19, "in progress"),
    (20, "in progress"),
    (21, "in progress"),
    (22, "in progress"),
    (23, "in progress"),
    (24, "in progress"),
    (25, "in progress"),
    (26, "in progress"),
    (27, "in progress"),
    (28, "in progress"),
    (29, "in progress"),
    (30, "in progress"),
    (31, "in progress"),
    (32, "in progress"),
    (33, "in progress"),
    (34, "in progress"),
    (35, "in progress"),
    (36, "in progress"),
    (37, "in progress"),
    (38, "in progress"),
    (39, "in progress"),
    (40, "in progress"),
    (41, "in progress"),
    (42, "in progress"),
    (43, "in progress"),
    (44, "in progress"),
    (45, "in progress"),
    (46, "in progress"),
    (47, "in progress"), 
    (48, "in progress"), 
    (49, "in progress"), 
    (50, "in progress"), 
    (51, "in progress"),
    (52, "in progress"),
    (53, "in progress"),
    (54, "in progress"),
    (55, "in progress"),
    (56, "in progress"),
    (57, "in progress"),
    (58, "in progress"),
    (59, "in progress"),
    (60, "in progress"),
    (61, "in progress"),
    (62, "in progress"),
    (63, "in progress"),
    (64, "in progress"),
    (65, "in progress"),
    (66, "in progress"),
    (67, "in progress"),
    (68, "in progress"),
    (69, "in progress"),
    (70, "in progress"),
    (71, "in progress"),
    (72, "in progress"),
    (73, "in progress"),
    (74, "in progress"),
    (75, "in progress"),
    (76, "in progress"),
    (77, "in progress"),
    (78, "in progress"),
    (79, "in progress"),
    (80, "in progress"),
    (81, "in progress"),
    (82, "in progress"),
    (83, "in progress"),
    (84, "in progress"),
    (85, "in progress"),
    (86, "in progress"),
    (87, "in progress"),
    (88, "in progress"),
    (89, "in progress"),
    (90, "in progress"),
    (91, "in progress"),
    (92, "in progress"),
    (93, "in progress"),
    (94, "in progress"),
    (95, "in progress"),
    (96, "in progress"),
    (97, "in progress"),
    (98, "in progress"),
    (99, "in progress"),
    (100, "closed");

/* How the CVSS of a security task will determine the severity of the task */
INSERT INTO SecurityCvssSeverityMap(CVSS, Severity)
    VALUES
    (0.0, "Low"),
    (0.1, "Low"),
    (0.2, "Low"),
    (0.3, "Low"),
    (0.4, "Low"),
    (0.5, "Low"),
    (0.6, "Low"),
    (0.7, "Low"),
    (0.8, "Low"),
    (0.9, "Low"),
    (1.0, "Low"),
    (1.1, "Low"),
    (1.2, "Low"),
    (1.3, "Low"),
    (1.4, "Low"),
    (1.5, "Low"),
    (1.6, "Low"),
    (1.7, "Low"),
    (1.8, "Low"),
    (1.9, "Low"),
    (2.0, "Low"),
    (2.1, "Low"),
    (2.2, "Low"),
    (2.3, "Low"),
    (2.4, "Low"),
    (2.5, "Low"),
    (2.6, "Low"),
    (2.7, "Low"),
    (2.8, "Low"),
    (2.9, "Low"),
    (3.0, "Low"),
    (3.1, "Low"),
    (3.2, "Low"),
    (3.3, "Low"),
    (3.4, "Low"),
    (3.5, "Low"),
    (3.6, "Low"),
    (3.7, "Low"),
    (3.8, "Low"),
    (3.9, "Low"),
    (4.0, "Medium"),
    (4.1, "Medium"),
    (4.2, "Medium"),
    (4.3, "Medium"),
    (4.4, "Medium"),
    (4.5, "Medium"),
    (4.6, "Medium"),
    (4.7, "Medium"),
    (4.8, "Medium"),
    (4.9, "Medium"),
    (5.0, "Medium"),
    (5.1, "Medium"),
    (5.2, "Medium"),
    (5.3, "Medium"),
    (5.4, "Medium"),
    (5.5, "Medium"),
    (5.6, "Medium"),
    (5.7, "Medium"),
    (5.8, "Medium"),
    (5.9, "Medium"),
    (6.0, "Medium"),
    (6.1, "Medium"),
    (6.2, "Medium"),
    (6.3, "Medium"),
    (6.4, "Medium"),
    (6.5, "Medium"),
    (6.6, "Medium"),
    (6.7, "Medium"),
    (6.8, "Medium"),
    (6.9, "Medium"),
    (7.0, "High"),
    (7.1, "High"),
    (7.2, "High"),
    (7.3, "High"),
    (7.4, "High"),
    (7.5, "High"),
    (7.6, "High"),
    (7.7, "High"),
    (7.8, "High"),
    (7.9, "High"),
    (8.0, "High"),
    (8.1, "High"),
    (8.2, "High"),
    (8.3, "High"),
    (8.4, "High"),
    (8.5, "High"),
    (8.6, "High"),
    (8.7, "High"),
    (8.8, "High"),
    (8.9, "High"),
    (9.0, "Critical"),
    (9.1, "Critical"),
    (9.2, "Critical"),
    (9.3, "Critical"),
    (9.4, "Critical"),
    (9.5, "Critical"),
    (9.6, "Critical"),
    (9.7, "Critical"),
    (9.8, "Critical"),
    (9.9, "Critical"),
    (10.0, "Critical");


/* How the type of a notification will determine the descirption of the notificaiton */
INSERT INTO NotificationTypeDescMap(Type, Description)
    VALUES
    ("Request", "A user has requested to join your team!"),
    ("Approval", "Your request to join a team has been approved!"),
    ("Denial", "Your request to join a team has been denied."),
    ("Addition", "A new user joined your team!"),
    ("Deletion", "A user has left your team.");

INSERT INTO Role(RoleName) 
    VALUES 
    ("Frontend Developer"),
    ("Backend Developer"),
    ("Designer"),
    ("Project Manager"),
    ("QA");